FROM ubuntu:20.04 AS builder-image

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --no-install-recommends -y python3 python3-dev python3-pip python3-wheel git && \
	apt-get clean && rm -rf /var/lib/apt/lists/*
RUN ln -sv /usr/bin/python3 /usr/bin/python

# create a non-root user
RUN useradd -ms /bin/bash apprunner
USER apprunner
WORKDIR /home/apprunner

ENV PATH="/home/appuser/.local/bin:${PATH}"
COPY ./requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY ./download_code.sh .
